name: Tests
on:
  push:
    branches:
      - features

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build an image
        run: |
          docker build -t strengen/monitoring-service .

      - name: Run tests
        run: |
          docker run --rm strengen/monitoring-service pytest

      - name: Smoke test
        run: |
          docker run --name test_container -d -p 5000:5000 strengen/monitoring-service
          sleep 5
          curl -f http://localhost:5000/health || exit 1
          docker stop test_container
          docker rm test_container

      - name: Build and run docker image
        run: |
          docker run -d --name test_container -p 5000:5000 .
          curl -f http://localhost:5000/health || exit 1
          exec test_container pytest
          docker stop test_container
          docker rm test_container
      
      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push strengen/monitoring-service